version: '3.8'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - redis
    networks:
      - my-app-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - my-app-network

networks:
  my-app-network:
    driver: bridge
