name: Build and Deploy
on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build Docker image
      run: docker build -t my-app .
    - name: Deploy to server
      run: |
        docker stop my-app || true
        docker rm my-app || true
        docker run -d --name my-app -p 3000:3000 my-app